# Generated by Django 4.1.5 on 2023-01-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='map_link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
